### ISSUE TITLE
It can't deal with rotated video source

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow-ofx#12]
If input video has 180 degree rotation tags it doubles all shakes instead of smoothing them. Workaround is to put two transform nodes in Fusion before and after Gyroflow node both rotating the frame 180 degree.

**Comment by ghuser123321** [comment]
I think the core issue is that both Resolve and OFX read video rotation tags and both rotate. Wouldn't it be the correct behavior of the OFX to assume that the host application will deal with rotation? Shouldn't it ignore rotation from .gyroflow file?

**Comment by carbendi** [comment]
I am having the same problem and I think "export with processed gyro data" is not including the rotation info. It would be nice to have it baked to the .gyroflow file if possible.

**Comment by AdrianEddy** [comment]
Done in latest version, please test if it works for your case:

https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-windows.zip
https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-linux.zip
https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-macosx.zip

**Comment by schachfeld** [comment]
I think I have the same error with footage shot by the insta360 go 2. I'm not sure but everything is even jankier when using the plugin than the original. In gyroflow the image is perfectly stabilized.
I tried adjusting the Rotation in gyrowflow, as well as the IMU orientation as a workaround. This made things better but did not completely resolve the issue.
Unfortunately the fusion integration is to slow to use the workaround for me :/

**Comment by AdrianEddy** [comment]
@schachfeld this issue is now fixed and Insta360 is also sync-less now, so it works directly in the plugin, without the need for the app 

https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-windows.zip
https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-linux.zip
https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-macosx.zip
https://gyroflow.xyz/devbuild/?autodownload
