### ISSUE TITLE
Occasional crash when DaVinci Color Page gets opened

### ISSUE THREAD

**Issue by muepla** [gyroflow/gyroflow-ofx#28]
@AdrianEddy 
As mentioned before, the plugin works really, really well on my Windows machine but I do experience an occasional crash when I open DaVinci's  "Color Page" in a project that has lots of GyroFlow stabilized videos.

I can't reproduce this reliably, but I believe this happens when DaVinci is rendering video thumbnails of all clips which results in Gyroflow having to allocate a lot of dedicated GPU memory at once. 

How does the plugin handle failed memory allocations ?

**Comment by AdrianEddy** [comment]
Hmm, I couldn't reproduce this, I tried a project with over 100 different gopro clips, all with gyroflow plugin
The resources are cached as much as possible, meaning that the GPU processing instances are created only when resolution changes. So for example all clips on a 1920x1080 timeline will only allocate one GPU processing engine and gpu memory.

Do you have many different timelines with different resolutions in your project? 
Can you confirm it happens when the memory level raises too much?

Let me know if you have any further details to reproduce this

**Comment by muepla** [comment]
Yes, the crashes on my machine are probably unrelated to Gyroflow: I had a similar crash when DaVinci created a lot of thumbnails in the "Media Pool" window of the DaVinci Edit page. The symptoms are always the same: DaVinci tries to render hundreds of thumbnails at once, the fan speed of the GPU ramps up, then the computer gets silent and a couple of seconds later DaVinci shuts down.
